spring:
  datasource:
    username: traffic
    password: traffic
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/traffic
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguratio
  mail:
    host: smtp.gmail.com  #需替換為實際郵箱服務器，這裡是公司的不能商用
    port: 587   #郵箱服務器端口號
    default-encoding: utf-8
    username: takeabuy@gmail.com  #郵箱認證賬號，對於公司郵箱使用工號
    password: buy88888  #郵箱密碼
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls:
            enable: true
            required: true
logging:
  config: classpath:logback-dev.xml
api:
  base_url_route_api: https://pixord.wiadvancelabs.com/osrm
license:
  encode_rule: '!#traffic@$3'
ids:
  speed_status_limit: 50
  space_status_limit: 80
  dayuan:
    east_id: 68000108011
    west_id: 68000108010
    start_intersection_id: H33700401
    end_intersection_id: H33701801
  basic_speed: 30
mail:
  sender: takeabuy@gmail.com #這裡需要替換為實際郵件發送者
traffic:
  domain: http://localhost:80 #這裡替換為實際的域名
  time_zone: GMT+8:00
server:
  port: 80
  
#logging:
#  level:
#    com.wistron.swpc.wismarttrafficlight.mapper: debug